services:
  - type: web
    name: starwalkin-bot
    env: node
    plan: free
    branch: main
    rootDir: .
    buildCommand: cd discord-bot && npm install
    startCommand: cd discord-bot && node index.js
    autoDeploy: true
