services:
  - type: web
    name: starwalkin-bot
    env: node
    plan: free
    branch: main
    rootDir: discord-bot        # ✅ 폴더 경로 추가!
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
