services:
  - type: web
    name: starwalkin-bot
    env: node
    plan: free
    branch: main
    rootDir: .         # ✅ 여기가 핵심
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
